using UnityEngine;
using System;
using System.Collections.Generic;
using UnityEngine.Serialization;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace Landscaper
{
	public enum TextureMaskMode
	{
		Texture,
		TextureIndex,
#if UNITY_2018_3_OR_NEWER
		TerrainLayer,
#endif
	}

	public enum MaskDensityCombineMode
	{
		Blend,
		Min,
		Max,
	}


	/// <summary>
	/// Descibes a species of foliage to be placed
	/// </summary>
	[Serializable]
	public sealed class FoliageSpecies : ScriptableObject, ISerializationCallbackReceiver
	{
		public static int CurrentFileVersion = 2;


		/// <summary>
		/// A list of possible archetypes to place; one will be picked at random for each foliage instance that is placed
		/// </summary>
		public List<FoliageArchetype> Archetypes = new List<FoliageArchetype>();

		/// <summary>
		/// If true, instances placed with the GameObject method will conform to the normal of the surface they were planted on
		/// </summary>
		public bool ConformToMeshSurface = true;

		/// <summary>
		/// Density used when planting the initial set of seeds - expressed as seeds per unit^2 (ignores Y component)
		/// </summary>
		public float InitialSeedDensity = 0.0003f;

		/// <summary>
		/// How far a seed can travel from the instance that spawned it
		/// </summary>
		public float MaxSeedTravelDistance = 10;

		/// <summary>
		/// The desired minimum number of child instances this piece of foliage can have
		/// </summary>
		public int MinChildren = 1;

		/// <summary>
		/// The maximum number of child instances this piece of foliage can have
		/// </summary>
		public int MaxChildren = 3;

		/// <summary>
		/// The collision radius for this species, no other instance can be placed within this area
		/// </summary>
		public float CollisionRange = 1.0f;

		/// <summary>
		/// Squared collision range stored & used to improve performance
		/// </summary>
		[HideInInspector]
		public float CollisionRangeSq;

		/// <summary>
		/// The radius of the shade generated by an instance of this species; other foliage cannot
		/// grow in this area unless they are set to be able to grow in shade
		/// </summary>
		public float ShadeRange = 5.0f;

		/// <summary>
		/// Squared shade range stored & used to improve performance
		/// </summary>
		[HideInInspector]
		public float ShadeRangeSq;

		/// <summary>
		/// Can this species grow in shade? If not, instances of this species cannot grow in the shade created by other foliage
		/// </summary>
		public bool CanGrowInShade;

		/// <summary>
		/// Minimum scale multiplier for random size variation
		/// </summary>
		public float MinScaleMultiplier = 0.7f;

		/// <summary>
		/// Maximum scale multiplier for random size variation
		/// </summary>
		public float MaxScaleMultiplier = 1.0f;

		/// <summary>
		/// The minimum surface angle that this species can grow on. Used for ensuring instances only grow on cliff faces, for example
		/// </summary>
		public float MinSlopeAngle = 0.0f;

		/// <summary>
		/// The maximum surface angle that this species can grow on. Prevents instances from growing on cliff faces
		/// </summary>
		public float MaxSlopeAngle = 30.0f;

		/// <summary>
		/// The minimum altitude this species can grow at, expressed as Y position in world-space
		/// </summary>
		public float MinAltitude = -1000;

		/// <summary>
		/// The maximum altitude this species can grow at, expressed as Y position in world-space
		/// </summary>
		public float MaxAltitude = 1000;

		/// <summary>
		/// Information specific to each generation
		/// </summary>
		public List<FoliageGeneration> Generations = new List<FoliageGeneration>();

		/// <summary>
		/// How layers are specified. By the terrain layer itself, the diffuse texture, or the texture index from the splatmap
		/// </summary>
#if UNITY_2018_3_OR_NEWER
		[FormerlySerializedAs("MaskMode")]
		public TextureMaskMode LayerMode = TextureMaskMode.TerrainLayer;
#else
		[FormerlySerializedAs("MaskMode")]
		public TextureMaskMode LayerMode = TextureMaskMode.Texture;
#endif

		/// <summary>
		/// How multiple conflicting layer densities are resolved.
		/// Blend:	Blends density values based on the strength of each layer.
		///			E.g. 60% grass with a density of 1 + 40% dirt with a density of 0.2 = (1 * 0.6) + (0.2 * 0.4) = 0.68
		///	Min:	The lowest density will be used.
		///	Max:	The highest density will be used.
		/// </summary>
		public MaskDensityCombineMode LayerDensityCombineMode = MaskDensityCombineMode.Blend;

		/// <summary>
		/// The default density multiplier to use for layers that don't appear in the layer density rules list
		/// </summary>
		public float DefaultLayerDensity = 0f;

		/// <summary>
		/// Used to determine how instances of this species can be placed on various terrain layers
		/// </summary>
		public List<TerrainLayerDensity> LayerDensityRules = new List<TerrainLayerDensity>();


		[SerializeField]
		private int fileVersion;


#region Deprecated

		/// <summary>
		/// Only used when MaskMode is set to 'Texture'
		/// If not empty, foliage instances of this species can only be applied to areas of terrain which use this texture
		/// </summary>
		[Obsolete("Removed in 1.4 - Use 'LayerDensityRules' instead")]
		public List<Texture2D> PlacementTextureMask = new List<Texture2D>();

		/// <summary>
		/// Only used when MaskMode is set to 'TextureIndex'
		/// If not empty, foliage instances of this species can only be applied to areas of terrain which have this texture index assigned in the splatmap
		/// </summary>
		[Obsolete("Removed in 1.4 - Use 'LayerDensityRules' instead")]
		public List<int> PlacementTextureIndexMask = new List<int>();

#endregion


		/// <summary>
		/// Returns information about a specific generation of foliage
		/// </summary>
		/// <param name="generation">The generation</param>
		/// <returns>Information about this generation</returns>
		public FoliageGeneration GetGeneration(int generation)
		{
			// If there are no generations set up, return the default information..
			if (Generations.Count == 0)
				return FoliageGeneration.None;
			else
			{
				// ..otherwise, return the information from the list (clamping generation to last element in the array)
				generation = Mathf.Clamp(generation, 0, Generations.Count - 1);
				return Generations[generation];
			}
		}

		/// <summary>
		/// Returns the expected archetype for a given generation
		/// </summary>
		/// <param name="randomStream">The random number stream used to get a random prefab</param>
		/// <param name="generation">The generation</param>
		/// <returns>Archetype to use for this generation</returns>
		public FoliageArchetype GetRandomArchetype(System.Random randomStream, int generation)
		{
			var gen = GetGeneration(generation);

			// If this generation has override archetypes, use one of those..
			if (gen.IsEnabled && gen.OverrideArchetypes.Count > 0)
				return GetWeightedRandomArchetype(gen.OverrideArchetypes, randomStream);
			// ..otherwise, pick from the default list
			else
				return GetWeightedRandomArchetype(Archetypes, randomStream);
		}

		private FoliageArchetype GetWeightedRandomArchetype(List<FoliageArchetype> archetypes, System.Random randomStream)
		{
			float totalWeight = 0f;

			// Calculate total weight
			foreach (var archetype in archetypes)
				if (archetype.Prefab != null)
					totalWeight += archetype.Weight;


			float randomNumber = (float)(randomStream.NextDouble() * totalWeight);

			foreach (var archetype in archetypes)
				if (archetype.Prefab != null)
				{
					if (randomNumber < archetype.Weight)
						return archetype;
					else
						randomNumber -= archetype.Weight;
				}

			return null;
		}


		#region ISerializationCallbackReceiver

		public void OnBeforeSerialize()
		{
			fileVersion = CurrentFileVersion;
		}

		public void OnAfterDeserialize()
		{
			// Update texture masks to the new data format
			if (fileVersion < 2)
			{
#pragma warning disable 0618
				if (LayerMode == TextureMaskMode.Texture && PlacementTextureMask.Count > 0)
				{
					DefaultLayerDensity = 0.0f;

					foreach (var texture in PlacementTextureMask)
						LayerDensityRules.Add(new TerrainLayerDensity(texture, 1f));
				}
				else if (LayerMode == TextureMaskMode.TextureIndex && PlacementTextureIndexMask.Count > 0)
				{
					DefaultLayerDensity = 0.0f;

					foreach (var index in PlacementTextureIndexMask)
						LayerDensityRules.Add(new TerrainLayerDensity(index, 1f));
				}
#pragma warning restore 0618
			}

			fileVersion = CurrentFileVersion;
		}

#endregion

		#region Static Methods
#if UNITY_EDITOR
		/// <summary>
		/// Creates a new Species asset
		/// </summary>
		/// <returns>The newly created asset</returns>
		[MenuItem("Assets/Create/Landscaper/Species")]
		public static FoliageSpecies CreateNew()
		{
			return UnityUtil.CreateAsset<FoliageSpecies>();
		}
#endif
#endregion
	}
}
